In [1]:
#inport 
# using simple array using numpy
import numpy as np

In [2]:
array = [3,4,2,3,5]

In [3]:
narray = np.array(array)

In [4]:
narray

array([3, 4, 2, 3, 5])

In [5]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [6]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [7]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [9]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])